import { useState } from 'react';
import { CalendarDays, Check, ClipboardPenLine, FileText, LockKeyhole, MapPin, Plus, RefreshCw, ShieldCheck, UserRound } from 'lucide-react';
import { motion } from 'motion/react';
import Button from '../components/ui/Button';
import { Carregando, MensagemErro, Vazio } from '../components/ui/Feedback';
import PageHeader from '../components/ui/PageHeader';
import { grupoEscalonado, itemEntrada, MOLA } from '../components/ui/animacoes';
import { useAsync } from '../hooks/useAsync';
import { criarPrescricao, listarPrescricoes, ORIGENS, obterPrescricao, renovarAcessoPrescricao } from '../services/prescricoesService';
import { formatarData } from '../utils/format';

const vazio = { titulo: '', origem: 'CONSULTA', dataAtendimento: '', profissional: '', registroProfissional: '', local: '', validadeAte: '', arquivoNome: '', observacoes: '', medicamentos: [{ nome: '', posologia: '', duracao: '' }] };

export default function Prescricoes() {
  const estado = useAsync(listarPrescricoes, []);
  const [formAberto, setFormAberto] = useState(false);
  const [form, setForm] = useState(vazio);
  const [selecionada, setSelecionada] = useState(null);
  const [aviso, setAviso] = useState('');
  const [processando, setProcessando] = useState(null);

  async function abrir(prescricao) {
    setAviso(''); setProcessando(`abrir-${prescricao.id}`);
    try { setSelecionada(await obterPrescricao(prescricao.id)); } catch (e) { setAviso(e.message); } finally { setProcessando(null); }
  }
  async function renovar(prescricao) {
    setProcessando(`renovar-${prescricao.id}`); setAviso('');
    try { setSelecionada(await renovarAcessoPrescricao(prescricao.id)); setAviso('Acesso renovado por mais 15 minutos.'); estado.recarregar(); } catch (e) { setAviso(e.message); } finally { setProcessando(null); }
  }
  async function salvar(e) {
    e.preventDefault(); setProcessando('salvar'); setAviso('');
    try { await criarPrescricao(form); setForm(vazio); setFormAberto(false); estado.recarregar(); setAviso('Prescrição adicionada com acesso protegido por 15 minutos.'); } catch (e) { setAviso(e.message); } finally { setProcessando(null); }
  }
  const dados = estado.dados;
  return <div className="mx-auto max-w-6xl">
    <PageHeader titulo="Prescrições" subtitulo="Receitas e orientações médicas em um só lugar." acao={<Button tamanho="sm" icone={Plus} onClick={() => setFormAberto((v) => !v)}>{formAberto ? 'Fechar' : 'Adicionar prescrição'}</Button>} />
    <p className="sr-only" role="status" aria-live="polite">{aviso}</p>
    {aviso && <motion.p initial={{ opacity: 0, y: -6 }} animate={{ opacity: 1, y: 0 }} transition={MOLA} className="mb-5 flex items-center gap-2 rounded-2xl bg-salvia-100 px-4 py-3 text-sm font-medium text-acento"><Check size={17} aria-hidden="true" /> {aviso}</motion.p>}
    {formAberto && <Formulario form={form} setForm={setForm} salvar={salvar} processando={processando === 'salvar'} cancelar={() => setFormAberto(false)} />}
    {estado.carregando && !dados ? <Carregando texto="Carregando prescrições..." /> : estado.erro ? <MensagemErro mensagem={estado.erro.message} onTentarNovamente={estado.recarregar} /> : dados?.length === 0 ? <Vazio icone={ClipboardPenLine} titulo="Nenhuma prescrição salva" descricao="Adicione uma receita recebida em consulta, após exame ou no pronto-socorro." acao={<Button icone={Plus} onClick={() => setFormAberto(true)}>Adicionar prescrição</Button>} /> : <motion.div className="grid grid-cols-1 gap-4 lg:grid-cols-2" variants={grupoEscalonado} initial="initial" animate="animate">{dados?.map((p) => <Card key={p.id} prescricao={p} abrir={() => abrir(p)} renovar={() => renovar(p)} processando={processando} />)}</motion.div>}
    {selecionada && <Detalhe prescricao={selecionada} fechar={() => setSelecionada(null)} />}
    <div className="mt-6 flex gap-3 rounded-2xl bg-ambar-50 px-4 py-3 text-sm text-ambar-800"><ShieldCheck size={20} className="shrink-0" aria-hidden="true" /><p>O documento fica disponível por 15 minutos após uma confirmação. A validade da receita é a data informada pelo profissional.</p></div>
  </div>;
}

function Card({ prescricao: p, abrir, renovar, processando }) { return <motion.article variants={itemEntrada} className="glass-strong rounded-[1.5rem] p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-lilas-100 text-lilas-600"><ClipboardPenLine size={22} aria-hidden="true" /></span><div className="min-w-0"><h2 className="break-words font-semibold">{p.titulo}</h2><p className="text-sm text-salvia-600">{p.origemRotulo} · {formatarData(p.dataAtendimento)}</p></div></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold ${p.acessoExpirado ? 'bg-ambar-50 text-ambar-800' : 'bg-salvia-100 text-acento'}`}>{p.acessoExpirado ? 'Acesso expirado' : 'Protegida'}</span></div><div className="mt-4 space-y-2 text-sm text-salvia-600"><p className="flex gap-2"><UserRound size={16} aria-hidden="true" /> {p.profissional}{p.registroProfissional && ` · ${p.registroProfissional}`}</p><p className="flex gap-2"><MapPin size={16} aria-hidden="true" /> {p.local}</p><p className="flex gap-2"><CalendarDays size={16} aria-hidden="true" /> Receita válida até {formatarData(p.validadeAte)}</p></div><div className="mt-4 flex flex-wrap gap-2"><Button tamanho="sm" icone={p.acessoExpirado ? RefreshCw : LockKeyhole} carregando={processando === `abrir-${p.id}` || processando === `renovar-${p.id}`} onClick={p.acessoExpirado ? renovar : abrir}>{p.acessoExpirado ? 'Renovar acesso' : 'Ver prescrição'}</Button><span className="inline-flex items-center gap-1.5 rounded-full bg-superficie/60 px-3 py-2 text-xs text-salvia-600"><FileText size={14} aria-hidden="true" /> {p.medicamentos.length} medicamento(s)</span></div></motion.article> }

function Detalhe({ prescricao: p, fechar }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-petroleo-950/45 p-4" role="dialog" aria-modal="true" aria-labelledby="titulo-prescricao"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-[1.75rem] bg-superficie p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h2 id="titulo-prescricao" className="text-xl font-semibold">{p.titulo}</h2><p className="mt-1 text-sm text-salvia-600">Documento protegido · acesso válido até {new Date(p.acessoValidoAte).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}</p></div><button type="button" onClick={fechar} className="rounded-full p-2 text-salvia-600 hover:bg-superficie/70" aria-label="Fechar">×</button></div><div className="mt-5 rounded-2xl bg-nevoa-100 p-4 text-sm"><p className="font-semibold">{p.profissional}</p><p className="text-salvia-600">{p.local} · {formatarData(p.dataAtendimento)}</p></div><h3 className="mt-5 font-semibold">Medicamentos</h3><div className="mt-2 space-y-2">{p.medicamentos.map((m, i) => <div key={`${m.nome}-${i}`} className="rounded-2xl bg-superficie/60 p-3 ring-1 ring-borda"><p className="font-medium">{m.nome}</p><p className="text-sm text-salvia-600">{m.posologia}{m.duracao && ` · ${m.duracao}`}</p></div>)}</div>{p.arquivoNome && <p className="mt-5 flex items-center gap-2 text-sm text-salvia-600"><FileText size={16} aria-hidden="true" /> Arquivo: {p.arquivoNome}</p>}<p className="mt-5 text-xs text-salvia-600">Demonstração: siga sempre a prescrição original e confirme dúvidas com um profissional de saúde.</p><Button bloco className="mt-5" onClick={fechar}>Fechar</Button></div></div> }

function Formulario({ form, setForm, salvar, processando, cancelar }) { const alterar = (campo, valor) => setForm((f) => ({ ...f, [campo]: valor })); const alterarMed = (i, campo, valor) => setForm((f) => ({ ...f, medicamentos: f.medicamentos.map((m, n) => n === i ? { ...m, [campo]: valor } : m) })); return <form onSubmit={salvar} className="glass-strong mb-6 rounded-[1.5rem] p-5"><h2 className="text-lg font-semibold">Adicionar prescrição</h2><p className="mt-1 text-sm text-salvia-600">Cadastre os dados exatamente como aparecem na receita.</p><div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2"><Campo label="Título" value={form.titulo} onChange={(v) => alterar('titulo', v)} required placeholder="Ex.: Receita da consulta" /><label className="text-sm font-medium">Origem<select className="mt-1 h-11 w-full rounded-xl bg-superficie px-3 ring-1 ring-borda" value={form.origem} onChange={(e) => alterar('origem', e.target.value)}>{Object.entries(ORIGENS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><Campo label="Data do atendimento" type="date" value={form.dataAtendimento} onChange={(v) => alterar('dataAtendimento', v)} required /><Campo label="Validade da receita" type="date" value={form.validadeAte} onChange={(v) => alterar('validadeAte', v)} required /><Campo label="Profissional" value={form.profissional} onChange={(v) => alterar('profissional', v)} required placeholder="Nome completo" /><Campo label="Registro profissional" value={form.registroProfissional} onChange={(v) => alterar('registroProfissional', v)} placeholder="Ex.: CRM-SP 000000" /><Campo label="Local" value={form.local} onChange={(v) => alterar('local', v)} required placeholder="Clínica, hospital ou pronto-socorro" /><Campo label="Arquivo (opcional)" value={form.arquivoNome} onChange={(v) => alterar('arquivoNome', v)} placeholder="Nome do PDF ou foto" /></div><div className="mt-4"><h3 className="font-semibold">Medicamentos</h3>{form.medicamentos.map((m, i) => <div className="mt-2 grid grid-cols-1 gap-2 rounded-2xl bg-superficie/50 p-3 sm:grid-cols-3" key={i}><Campo label="Medicamento" value={m.nome} onChange={(v) => alterarMed(i, 'nome', v)} required placeholder="Nome" /><Campo label="Posologia" value={m.posologia} onChange={(v) => alterarMed(i, 'posologia', v)} placeholder="Dose e frequência" /><Campo label="Duração" value={m.duracao} onChange={(v) => alterarMed(i, 'duracao', v)} placeholder="Ex.: 7 dias" /></div>)}<button type="button" className="mt-2 text-sm font-semibold text-acento" onClick={() => setForm((f) => ({ ...f, medicamentos: [...f.medicamentos, { nome: '', posologia: '', duracao: '' }] }))}>+ Adicionar medicamento</button></div><div className="mt-5 flex justify-end gap-2"><Button type="button" variante="fantasma" onClick={cancelar}>Cancelar</Button><Button type="submit" carregando={processando}>Salvar prescrição</Button></div></form> }
function Campo({ label, value, onChange, ...props }) { return <label className="text-sm font-medium">{label}<input className="mt-1 h-11 w-full rounded-xl bg-superficie px-3 text-base ring-1 ring-borda outline-none focus:ring-2 focus:ring-acento" value={value} onChange={(e) => onChange(e.target.value)} {...props} /></label>; }
